apiVersion: v1
kind: ConfigMap
metadata:
  name: es-configmap
  namespace: zcp-logging
data:
  master.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: true
    node.data: false
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"

  data.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: false
    node.data: true
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"

  client.yml: |-
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    discovery.zen.ping.unicast.hosts: elasticsearch-discovery
    discovery.zen.minimum_master_nodes: 1
    node.master: false
    node.data: false
    xpack.security.enabled: false
    http:
      host: 0.0.0.0
      enabled: true
      compression: true
      cors:
        enabled: true
        allow-origin: "*"
