apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-data-0
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    app: elasticsearch
    component: elasticsearch
    role: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ibmc-block-retain-silver

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-data-1
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    app: elasticsearch
    component: elasticsearch
    role: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ibmc-block-retain-silver

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-data-2
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-retain-silver
  labels:
    app: elasticsearch
    component: elasticsearch
    role: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ibmc-block-retain-silver