replicaCount: 1

image:
  repository: jboss/keycloak-proxy
  tag: 4.2.0.Final
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  annotations:
    ingress.bluemix.net/redirect-to-https: "True"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - cbt-logging.cloudzcp.io
  tls: 
    - secretName: cloudzcp-io-cert
      hosts:
        - cbt-logging.cloudzcp.io

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

affinity: {}

tolerations:
- key: "management"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"
restartPolicy: Always
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - "amd64"
        - key: role
          operator: In
          values:
          - "management"

configmap:
  targetUrl: http://kibana:5602/
  realm: zcp
  realmPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqoXh3oUvc2t20er1bIsoWipAXF2XRAjwfi+t4quDNOgYnzriAci3/xpI1+TfgdD4KgxENZJE+zu+tdz1TMz6WpxcjAGu6rRtlkE3l8X+HGSORvQpyy0Dl7AImo0aEUARgsD9TBachHfjUo/oQW1PaGgi8Nt8eG6pOjSiNbYIW9esxgoYLUbiqkZflEfx8iXuLiEw73trTeZwzqpAFMgmkAhCf8l+FCiQdbUQv4LW2G6S6jxooM6MEhvmzYM4z/yTmo4+d32YsNrWZGFIxgaOS58Eez2YQ5IH+RzV5whPsvIGRxvYiPgEChPJpKOZwOQNkQPwzMoteSqYIeGyeWDdHwIDAQAB"
  authServerUrl: https://cbt-iam.cloudzcp.io/auth
  resource: logging
  secret: 69ca391e-4999-4779-96cc-6aef4875ea46
  pattern: /*	
  rolesAllowed: admin
