apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: zcp-logging
data:
  logstash.yml: |-
    config.reload.automatic: true
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
    log.level: info
    path.logs: /usr/share/logstash
