apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: logstash
    component: logstash
  name: logstash
  namespace: zcp-system
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: logstash
    spec:
      tolerations:
#      - key: "dedicated"
#        operator: "Exists"
#        effect: "NoSchedule"
      - key: "LoggingNode"
        operator: "Equal"
        value: "log"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
              - key: logging
                operator: In
                values:
                - "true"
      containers:
      - env:
        - name: LS_JAVA_OPTS
          value: -Xmx256m -Xms256m
        image: "ibmcom/logstash:5.5.1"
        resources:
          limits:
            memory: "512M"
        name: logstash
        ports:
        - containerPort: 5044
        resources: {}
        volumeMounts:
        - name: pipeline-config
          mountPath: /usr/share/logstash/pipeline
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: data
          mountPath: /usr/share/logstash/data
      restartPolicy: Always
      volumes:
      - name: pipeline-config
        configMap:
          name: logstash-pipeline
      - name: config
        configMap:
          name: logstash-config
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: data
        emptyDir:
          medium: ""
