apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data-elasticsearch-data-2
  annotations:
    volume.beta.kubernetes.io/storage-class: ibmc-block-silver
  labels:
    app: elasticsearch
    component: elasticsearch
    role: data
    billingType: "hourly"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-block-silver
