apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: filebeat
    component: filebeat
  name: filebeat-ds-config
  namespace: logging
data:
  filebeat.yml: |-
    filebeat.prospectors:
    -
      input_type: log
      paths:
        - /var/lib/docker/containers/*/*.log
      scan_frequency: 10s
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      fields_under_root: true
      scan_frequency: 10s
      # Attach this type field to this prospector for the managed daemonset
      fields:
        type: kube-logs
      tags:
        - k8s-app

    filebeat.config.modules:
      # Set to true to enable config reloading
      reload.enabled: true

    output.logstash:
      hosts:
        - "logstash:5044"

    logging.level: info
