apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: zcp-system
  labels:
    app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: fluent-bit
        image: registry.au-syd.bluemix.net/cloudzcp/fluent-bit:0.13.4
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
#        - name: FLUENT_ELASTICSEARCH_HOST
#          value: "elasticsearch"
#        - name: FLUENT_ELASTICSEARCH_PORT
#          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/data/cripersistentstorage/containers/ 
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/data/cripersistentstorage/containers/
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: zcp-system-admin
#      imagePullSecrets:
#        - name: bluemix-cloudzcp-secret
      hostNetwork: true
