apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: kube-system
data:
  logstash.yml: |-
    config.reload.automatic: true
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false
