apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
    component: logstash
  name: logstash
  namespace: zcp-logging
spec:
  ports:
  - port: 5044
    targetPort: 5044
    name: beats
  selector:
    name: logstash
